spring:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:h2:file:./database/testDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

app:
  clientId: 52681983
